# server port configuration
server:
  port: 8225

# server context path configuration 
  servlet:
    context-path: /api

# database configuration
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#jpa and hibernate related configuration   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #update
    properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        
#logging configuration
logging:
  level:
    org.springframework.web: ERROR
    com.ecs.api : DEBUG

  pattern:
    #pattern for the console
    console: '%d{yyyy-MM-dd HH:mm:ss} [%p] :: [%t] [%C]  [%M] :: %m  %n'
    #pattern for the file
    file: '%d{yyyy-MM-dd HH:mm:ss} [%p] :: [%t] [%C]  [%M] :: %m  %n'
    
  #file path  
  file:
    path: ./log/
    name: ./log/ApiLogs.log
    max-size:
      5MB
 